# Generated by Django 2.2.3 on 2019-07-31 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kickstarter_campaign',
            old_name='pledge',
            new_name='pledged',
        ),
    ]
